// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyNhanSu.API.Data;

#nullable disable

namespace QuanLyNhanSu.API.Migrations
{
    [DbContext(typeof(QuanLyNhanSuDbContext))]
    partial class QuanLyNhanSuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyNhanSu.API.Models.BangLuong", b =>
                {
                    b.Property<int>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuong"));

                    b.Property<decimal>("LuongCoBan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<decimal>("SoNgayCong")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal>("TongKhauTru")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongLuong")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongPhuCap")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongThuong")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaLuong");

                    b.HasIndex("MaNV", "Thang", "Nam")
                        .IsUnique();

                    b.ToTable("BANGLUONG");
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.ChamCong", b =>
                {
                    b.Property<int>("MaCC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCC"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<TimeSpan?>("GioRa")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("GioVao")
                        .HasColumnType("time");

                    b.Property<int>("MaCa")
                        .HasColumnType("int");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayChamCong")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SoGioLam")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaCC");

                    b.HasIndex("MaCa");

                    b.HasIndex("MaNV");

                    b.ToTable("CHAMCONG");
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.ChucVu", b =>
                {
                    b.Property<int>("MaCV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCV"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenCV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaCV");

                    b.ToTable("CHUCVU");
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.HopDong", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHD"));

                    b.Property<decimal>("LuongCoBan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaLoaiHD")
                        .HasColumnType("int");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHD");

                    b.HasIndex("MaLoaiHD");

                    b.HasIndex("MaNV");

                    b.ToTable("HOPDONG");
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.KhenThuongKyLuat", b =>
                {
                    b.Property<int>("MaKTKL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKTKL"));

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LyDo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayQuyetDinh")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SoTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaKTKL");

                    b.HasIndex("MaNV");

                    b.ToTable("KHENTHUONGKYLUAT");
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.LoaiCa", b =>
                {
                    b.Property<int>("MaCa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCa"));

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<decimal>("SoGioQuyDinh")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TenCa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaCa");

                    b.ToTable("LOAICA");
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.LoaiHopDong", b =>
                {
                    b.Property<int>("MaLoaiHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiHD"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenLoaiHD")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoaiHD");

                    b.ToTable("LOAIHOPDONG");
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.LoaiNghiPhep", b =>
                {
                    b.Property<int>("MaLoaiNP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiNP"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenLoaiNP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoaiNP");

                    b.ToTable("LOAINGHIPHEP");
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.NghiPhep", b =>
                {
                    b.Property<int>("MaNP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNP"));

                    b.Property<DateTime>("DenNgay")
                        .HasColumnType("datetime2");

                    b.Property<string>("LyDo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaLoaiNP")
                        .HasColumnType("int");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiDuyet")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TuNgay")
                        .HasColumnType("datetime2");

                    b.HasKey("MaNP");

                    b.HasIndex("MaLoaiNP");

                    b.HasIndex("MaNV");

                    b.HasIndex("NguoiDuyet");

                    b.ToTable("NGHIPHEP");
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<string>("CCCD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaCV")
                        .HasColumnType("int");

                    b.Property<int?>("MaPB")
                        .HasColumnType("int");

                    b.Property<int?>("MaTD")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNV");

                    b.HasIndex("MaCV");

                    b.HasIndex("MaPB");

                    b.HasIndex("MaTD");

                    b.ToTable("NHANVIEN");
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.NhanVienPhuCap", b =>
                {
                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<int>("MaPC")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayApDung")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNV", "MaPC");

                    b.HasIndex("MaPC");

                    b.ToTable("NHANVIEN_PHUCAP");
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.PhongBan", b =>
                {
                    b.Property<int>("MaPB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPB"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenPB")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPB");

                    b.ToTable("PHONGBAN");
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.PhuCap", b =>
                {
                    b.Property<int>("MaPC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPC"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenPC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPC");

                    b.ToTable("PHUCAP");
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.Quyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaQuyen");

                    b.ToTable("QUYEN");
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTK"));

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<int>("MaQuyen")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTK");

                    b.HasIndex("MaNV")
                        .IsUnique();

                    b.HasIndex("MaQuyen");

                    b.ToTable("TAIKHOAN");
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.TrinhDo", b =>
                {
                    b.Property<int>("MaTD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTD"));

                    b.Property<string>("TenTD")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTD");

                    b.ToTable("TRINHDO");
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.BangLuong", b =>
                {
                    b.HasOne("QuanLyNhanSu.API.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.ChamCong", b =>
                {
                    b.HasOne("QuanLyNhanSu.API.Models.LoaiCa", null)
                        .WithMany()
                        .HasForeignKey("MaCa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyNhanSu.API.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.HopDong", b =>
                {
                    b.HasOne("QuanLyNhanSu.API.Models.LoaiHopDong", null)
                        .WithMany()
                        .HasForeignKey("MaLoaiHD")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyNhanSu.API.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.KhenThuongKyLuat", b =>
                {
                    b.HasOne("QuanLyNhanSu.API.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.NghiPhep", b =>
                {
                    b.HasOne("QuanLyNhanSu.API.Models.LoaiNghiPhep", null)
                        .WithMany()
                        .HasForeignKey("MaLoaiNP")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyNhanSu.API.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyNhanSu.API.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("NguoiDuyet")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.NhanVien", b =>
                {
                    b.HasOne("QuanLyNhanSu.API.Models.ChucVu", null)
                        .WithMany()
                        .HasForeignKey("MaCV")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyNhanSu.API.Models.PhongBan", null)
                        .WithMany()
                        .HasForeignKey("MaPB")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyNhanSu.API.Models.TrinhDo", null)
                        .WithMany()
                        .HasForeignKey("MaTD")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.NhanVienPhuCap", b =>
                {
                    b.HasOne("QuanLyNhanSu.API.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyNhanSu.API.Models.PhuCap", null)
                        .WithMany()
                        .HasForeignKey("MaPC")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyNhanSu.API.Models.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyNhanSu.API.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyNhanSu.API.Models.Quyen", null)
                        .WithMany()
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
